In [30]:
import torch
import torch.nn.functional as F
from torch import nn

in_ = torch.rand(2, 5)
weights = torch.tensor(
    [[
        [1, 0],
        [1, 2],
    ]], dtype=torch.float32
)
in_, weights

(tensor([[0.4862, 0.1813, 0.8873, 0.8159, 0.2518],
         [0.4877, 0.1386, 0.7595, 0.7164, 0.9861]]),
 tensor([[[1., 0.],
          [1., 2.]]]))

In [48]:
nn.AvgPool1d(2, stride=1)(in_)


tensor([[0.3337, 0.5343, 0.8516, 0.5338],
        [0.3132, 0.4491, 0.7380, 0.8513]])

In [40]:
out_

NameError: name 'out_' is not defined